plugin service
ConduitIO/conduit pull request #311
Opened 2022-03-21 14:15 UTC by maha-hajja

### Description

plugin service
plugin list API {GET /v1/plugins} or {GET /v1/plugins?name=s.*}
plugin orchestrator
mocks
mini proto changes
added "type" to plugin.parameter

Fixes # 118

### Quick checks:

- [ ] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [ ] There is no other [pull request](https://github.com/ConduitIO/conduit/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

2022-03-22 18:00 UTC, lovromazgon requested changes
Posted lots of comments but nothing major, generally it looks very good 👏  I would love to see some tests for the handler!

2022-03-22 18:08 UTC, lovromazgon commented on pkg/plugin/acceptance_testing.go
> +			"param2.1": {Default: "bar", Description: "Param 1.2 description", Validations: []Validation{{VType: ValidationTypeRequired}}},
We need to set the `Type` in the expectation, then tests should pass (well, and we need to address [this comment](https://github.com/ConduitIO/conduit/pull/311#discussion_r832454638), to make sure `Validations` are actually `nil` if there are none).
```suggestion
			"param1.1": {Default: "foo", Type: "string", Description: "Param 1.1 description"},
			"param2.1": {Default: "bar", Type: "string", Description: "Param 1.2 description", Validations: []Validation{{VType: ValidationTypeRequired}}},
```

2022-03-24 12:25 UTC, maha-hajja commented on pkg/web/api/toproto/plugin.go
> +func PluginValidationType(in plugin.ValidationType) apiv1.PluginSpecifications_Parameter_Validation_Type {
@lovromazgon will do! I noticed that connectors and processors use this trick.. but why not the pipelines?

2022-03-24 12:39 UTC, lovromazgon commented on pkg/web/api/toproto/plugin.go
> +func PluginValidationType(in plugin.ValidationType) apiv1.PluginSpecifications_Parameter_Validation_Type {
There the enums don't match 1 to 1, we have 2 different internal states for stopped, while the API only exposes a single stopped state.

2022-03-24 18:00 UTC, lovromazgon requested changes
The API plugin error function and handler test need some minor changes, after that I think we're good!

2022-03-24 21:17 UTC, maha-hajja commented on pkg/web/api/plugin_v1_test.go
> +	var plist []*apiv1.PluginSpecifications
it was deleted on the next commit

2022-03-25 11:30 UTC, lovromazgon commented on pkg/web/api/plugin_v1_test.go
> +	var plist []*apiv1.PluginSpecifications
Oh, my bad, I must have been looking at the changes without the last commit!

2022-03-25 14:40 UTC, lovromazgon approved these changes
Looks great 👍  Let's wait for Github actions to start running again and see if the build succeeds, then we can go ahead and merge this!

2022-03-25 16:03 UTC, merged